In [2]:
import pandas as pd

df = pd.read_csv("D:/DATA/aitpune/college study thingy/dsbdal/prac_exam_questions/12-descriptive-stats/winequality-red.csv")

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
grouped = df.groupby("quality")["alcohol"].agg(["mean", "median", "min", "max", "std"])

print("Summary Statistics (Alcohol grouped by Quality):\n")
print(grouped)

Summary Statistics (Alcohol grouped by Quality):

              mean  median  min   max       std
quality
3         9.955000   9.925  8.4  11.0  0.818009
4        10.265094  10.000  9.0  13.1  0.934776
5         9.899706   9.700  8.5  14.9  0.736521
6        10.629519  10.500  8.4  14.0  1.049639
7        11.465913  11.500  9.2  14.0  0.961933
8        12.094444  12.150  9.8  14.0  1.224011

In [4]:
value_list = df.groupby("quality")["alcohol"].apply(list)

print("\nList of alcohol values for each quality:\n")
print(value_list)

List of alcohol values for each quality:

quality
3    [9.0, 8.4, 10.7, 9.9, 11.0, 10.9, 9.8, 9.7, 10...
4    [9.0, 9.8, 9.3, 13.1, 9.2, 9.1, 10.5, 9.4, 9.2...
5    [9.4, 9.8, 9.8, 9.4, 9.4, 9.4, 10.5, 9.2, 10.5...
6    [9.8, 9.2, 9.4, 9.7, 9.8, 10.6, 9.4, 9.6, 10.8...
7    [10.0, 9.5, 10.5, 9.7, 9.5, 10.5, 13.0, 10.3, ...
8    [12.8, 12.6, 12.9, 9.8, 13.4, 11.7, 11.0, 11.0...
Name: alcohol, dtype: object

In [5]:
import seaborn as sns

iris = sns.load_dataset("iris")

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
iris["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [9]:
species_list = iris["species"].unique()

In [10]:
for sp in species_list:
    
    print(f"\nStatistics for {sp}:\n")
    
    subset = iris[iris["species"] == sp]
    
    print("Mean:\n", subset.mean(numeric_only=True))
    
    print("\nStandard Deviation:\n", subset.std(numeric_only=True))
    
    print("\nPercentiles:\n", subset.quantile([0.25, 0.5, 0.75], numeric_only=True))

Statistics for setosa:

Mean:
 sepal_length    5.006
sepal_width     3.428
petal_length    1.462
petal_width     0.246
dtype: float64

Standard Deviation:
 sepal_length    0.352490
sepal_width     0.379064
petal_length    0.173664
petal_width     0.105386
dtype: float64

Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25           4.8        3.200         1.400          0.2
0.50           5.0        3.400         1.500          0.2
0.75           5.2        3.675         1.575          0.3

Statistics for versicolor:

Mean:
 sepal_length    5.936
sepal_width     2.770
petal_length    4.260
petal_width     1.326
dtype: float64

Standard Deviation:
 sepal_length    0.516171
sepal_width     0.313798
petal_length    0.469911
petal_width     0.197753
dtype: float64

Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25           5.6        2.525          4.00          1.2
0.50           5.9        2.800          4.35          1.3
0.75           6.3        3.000          4.60          1.5

Statistics for virginica:

Mean:
 sepal_length    6.588
sepal_width     2.974
petal_length    5.552
petal_width     2.026
dtype: float64

Standard Deviation:
 sepal_length    0.635880
sepal_width     0.322497
petal_length    0.551895
petal_width     0.274650
dtype: float64

Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25         6.225        2.800         5.100          1.8
0.50         6.500        3.000         5.550          2.0
0.75         6.900        3.175         5.875          2.3